apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencript-prod
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: fondio@tacilent.ai
    privateKeySecretRef:
      name: letsencript-prod
    solvers:
      - http01:
          ingress:
            class: nginx
